name: Cross Compile including test

on: [pull_request, push]

jobs:
  cross-compilation-test:
    strategy:
      fail-fast: false
      matrix:
        # The platform matrix specifies the package to be loaded by apt,
        # then the cross compilation prefix and finally the configuration
        # target.
        platform: [
          {
            arch: aarch64-linux-gnu,
            libs: libc6-dev-arm64-cross,
            target: linux-aarch64 enable-fips
          }, {
            arch: alpha-linux-gnu,
            libs: libc6.1-dev-alpha-cross,
            target: linux-alpha-gcc enable-fips
          }, {
            arch: arm-linux-gnueabi,
            libs: libc6-dev-armel-cross,
            target: linux-armv4 enable-fips
          }, {
            arch: arm-linux-gnueabihf,
            libs: libc6-dev-armhf-cross,
            target: linux-armv4 enable-fips
          }, {
            arch: mips-linux-gnu,
            libs: libc6-dev-mips-cross,
            target: linux-mips32 enable-fips
          }, {
            arch: mipsel-linux-gnu,
            libs: libc6-dev-mipsel-cross,
            target: linux-mips32 no-fips
          }, {
            arch: powerpc64le-linux-gnu,
            libs: libc6-dev-ppc64el-cross,
            target: linux-ppc64le enable-fips
          }, {
            arch: riscv64-linux-gnu,
            libs: libc6-dev-riscv64-cross,
            target: linux64-riscv64 enable-fips
          }, {
            arch: s390x-linux-gnu,
            libs: libc6-dev-s390x-cross,
            target: linux64-s390x enable-fips
          }, {
            arch: sparc64-linux-gnu,
            libs: libc6-dev-sparc64-cross,
            target: linux64-sparcv9 no-fips
          }
        ]
    runs-on: ubuntu-latest
    steps:
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get -yq --force-yes install gcc-${{ matrix.platform.arch }} ${{ matrix.platform.libs }} qemu-user
    - uses: actions/checkout@v2
    - name: config
      run: ./config --banner=Configured --strict-warnings --cross-compile-prefix=${{ matrix.platform.arch }}- ${{ matrix.platform.target }} && perl configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: make test
      run: QEMU_LD_PREFIX=/usr/${{ matrix.platform.arch }} make test HARNESS_JOBS=${HARNESS_JOBS:-4} TESTS="-test_x509_store -test_includes -test_store"
